### PR TITLE
update to ember 2.0

### PR DESCRIPTION
**Pull request by null-null-null**
@firefly-ui/owners

### CODE REVIEW

**Comment by twokul** [comment]
I would hold off on that. @null-null-null any specific reason for an upgrade?

**Comment by null-null-null** [comment]
@twokul Bringing POS up to 2.0. Why hold off?

**Comment by pzuraq** [comment]
@twokul this change is backwards compat, think it's good to merge either way.

**Comment by twokul** [comment]
@null-null-null are you sure you're not gonna be supporting ie8?

**Comment by null-null-null** [comment]
@twokul That's a good point. We'd decided not to worry about IE8 unless one of our clients asked for it, but at the same time, we shouldn't preclude that support by jumping right onto 2.0. I'll hold off on updating POS until fastboot comes out.

For the time being, this PR is still backwards compatible, and to ensure `ui-sorter` remains that way, it's added 1.13 to the ember-try scenarios. This'll ensure that we can support both 1.13 and 2.0+, which should help us gain traction as an open-source project.

**Comment by pzuraq** [comment]
:+1: merging

**Comment by twokul** [comment]
@null-null-null my only question was about IE8, sorry to keep you waiting :confused: 
@pzuraq thanks for merging duder

**Comment by null-null-null** [comment]
@twokul No problem, and thanks for bringing my attention back to IE8 support. That could save me some grief in the long run.

**Pull request merged**
